
/*
 * This file was generated by the SOM Compiler.
 * FileName: lfolder.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define WPSLockedFolder_Class_Source
#include "lfolder.ih"

#define PASSWORD "demo"

MRESULT APIENTRY PasswordDlgProc(HWND, ULONG, MPARAM, MPARAM);

SOM_Scope HWND   SOMLINK wpOpen(WPSLockedFolder *somSelf,
		HWND hwndCnr,
		ULONG ulView,
		ULONG param)
{
    HMODULE hModule;

    WPSLockedFolderData *somThis = WPSLockedFolderGetData(somSelf);
    WPSLockedFolderMethodDebug("WPSLockedFolder","wpOpen");

    if (DosQueryModuleHandle("LFOLDER", &hModule) == 123)
    { 
       WinMessageBox(HWND_DESKTOP,
                     HWND_DESKTOP,
                     "DosQueryModuleHandle()",
                     NULL,
                     0,
                     MB_OK | MB_ERROR);
       return FALSE;
    }

    if (WinDlgBox(HWND_DESKTOP,
                  HWND_DESKTOP,
                  (PFNWP) PasswordDlgProc,
                  hModule,
                  PasswordDlgBox,
                  NULL))
      return (parent_wpOpen(somSelf,hwndCnr,ulView,param));
    else
      return FALSE;
}

MRESULT APIENTRY PasswordDlgProc(HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2)
{
    CHAR  szPW[20];

    switch(msg)
    {
      case WM_COMMAND:
        switch(SHORT1FROMMP(mp1))
        {
           case DID_OK:    
             WinQueryDlgItemText(hwnd, EF_PASSWORD, 20, szPW);
             WinDismissDlg(hwnd, (BOOL) !stricmp(szPW, PASSWORD));
             break;

           case DID_CANCEL:
             WinDismissDlg(hwnd, FALSE);
             break;
        }
        break;

      default:
        return WinDefDlgProc(hwnd, msg, mp1, mp2);
        break;
    }

    return FALSE;

}
